---
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: info@javasquare.cafe
baseurl: 
logo: "/images/logo.png"
favicon: assets/images/favicon.png
locale: en_us
ganalytics: UA-48421544-1
social: 
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
